// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {codegen} from '../models';

export function PingDb(arg1:codegen.DataSourceConfig):Promise<Array<codegen.DatabaseOptions>>;
