// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {crypt} from '../models';

export function Encode(arg1: crypt.Config): Promise<string>;
