import { IdType, NamingStrategy, StrategyConfig } from '@/types/type'

export const useStrategyConfig = defineStore('strategyConfigState', {
  state: (): StrategyConfig => ({
    isCapitalMode: false,
    skipView: false,
    tablePrefix: new Set(),
    tablesuffix: new Set(),
    fieldPrefix: new Set(),
    fieldsuffix: new Set(),
    include: new Set(),
    exclude: new Set(),
    enableSqlFilter: false,
    enableSchema: false,
    entity: {
      superClass: '',
      superEntityColumns: new Set(),
      ignoreColumns: new Set(),
      disableSerialVersionUid: false,
      columnContant: false,
      chainMode: false,
      lombok: false,
      booleanColumnRemoveIsPrefix: false,
      tableFieldAnnotationEnable: false,
      versionColumnName: '',
      versionPropertyName: '',
      logicDeleteColumnName: '',
      logicDeletePropertyName: '',
      tableFillList: [],
      naming: NamingStrategy.UNDERLINE_TO_CAMEL,
      activeRecord: false,
      idType: IdType.AUTO,
      fileOverride: true,
      formatFilename: '',
    },
    controller: {
      superClass: '',
      restStyle: false,
      hyphenStyle: false,
      fileOverride: true,
      formatFilename: '',
    },
    mapper: {
      superClass: '',
      mapperAnnotation: true,
      mapperAnnotationClass: '',
      baseResultMap: false,
      baseColumnList: false,
      fileOverride: true,
      formatMapperFilename: '',
      formatXmlFilename: '',
    },
    service: {
      superServiceClass: '',
      superServiceImplClass: '',
      fileOverride: true,
      formatServiceFilename: '',
      formatServiceImplFilename: '',
    },
  }),
  persistedState: {
  },
})
