// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {codegen} from '../models';

export function CodeGenerate(arg1:codegen.ConfigContext):Promise<string|Error>;
