name: tomato-toolkit build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: tomato-toolkit, platform: linux/amd64, os: ubuntu-latest},
          {name: tomato-toolkit, platform: windows/amd64, os: windows-latest},
          {name: tomato-toolkit, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dep
        run: cd frontend && npm install
      - name: setup node
        run: cd frontend && npm run build
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: 1.19
