name: tomato-toolkit build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
        #   {name: tomato-toolkit, os: ubuntu-latest},
          {name: tomato-toolkit, os: windows-latest},
        #   {name: tomato-toolkit, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.3
          run-install: false

      - name: Use Node.js 16.13
        uses: actions/setup-node@v2
        with:
          node-version: 16.13
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: |
          pnpm config set registry https://registry.npmmirror.com/
          cd frontend
          pnpm install --frozen-lockfile

      - name: Build frontend
        run: |
            cd frontend
            pnpm build

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Install wails dependencies
        run: |
          go env -w GOPROXY=https://goproxy.cn,direct
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails -v
          wails -doctor
          wails update -pre

      - name: Build tomato-toolkit
        run: |
          wails build -s -webview2 download
          
