on:
  push:
    tags:
      - 'v*'

name: Create release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: tomato-toolkit, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
            - cmd: [frontend]

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ matrix.build.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.build.os }}-pnpm-store-
      - name: Build frontend
        run: |
            cd frontend
            pnpm build
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: 1.19

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            build/bin/tomato-toolkit-amd64-installer.exe
            build/bin/tomato-toolkit.exe
