on:
  push:
    tags:
      - 'v*'

name: Create release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: tomato-toolkit, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dep
        run: |
            cd frontend
            pnpm install
      - name: Build frontend
        run: |
            cd frontend
            pnpm build
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: 1.19

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            build/bin/tomato-toolkit-amd64-installer.exe
            build/bin/tomato-toolkit.exe
